# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TASK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=240)),
                ('status', models.CharField(choices=[('N', 'New'), ('P', 'Pending'), ('D', 'Done')], default='N', max_length=1)),
            ],
        ),
    ]
